### ISSUE TITLE
problem occuring after a change in the GAP library concerning `MutableCopyMat` 

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/hap#104]
Since gap-system/gap/pull/5352 got merged, some tests of hap's test suite fail with error messages.
The reason is that hap calls `MutableCopyMat` (which had been documented only for certain objects from the cvec package) for lists that aren't matrices.
The test pass again when one replaces the `MutableCopyMat` calls in `lib/ModPRings/recordPartII.gi` by `ShallowCopy` calls.
(In these cases, `MutableCopyMat` is called for vectors of field elements, which had worked before just by chance.)

There are quite a few `MutableCopyMat` occurrences in the hap code, and I have not checked all of them.
In some places, calling `MutableCopyMat` is safe but one could simplify something like `MutableCopyMat([w])[1]`, for a list `w` of field elements, to `ShallowCopy(w)`.

**Comment by fingolfin** [comment]
@grahamknockillaree I made two PRs: one addresses the actual regression (fixing a place were `MutableCopyMat` was invoked on vectors, instead of matrices), the other removes a bunch of `MutableCopyMat` (either because they were redundant, or by calling other methods that make the call to `MutableCopyMat` unnecessary).
