### ISSUE TITLE
bug in GroupHomology

### ISSUE THREAD

**Issue by BrauerSuzuki** [gap-packages/hap#111]
I run into the following unexpected behaivor with HAP 1.55:
`G:=SmallGroup(120,47);`
`GroupHomology(G,2);`
`Error, usage: Group(<gen>,...), Group(<gens>), Group(<gens>,<id>)`

**Comment by grahamknockillaree** [comment]
Thanks for spotting this.  The bug is due to my misunderstanding of what Parent(G) means in GAP.  A fix is to replace line 269 in /hap-1.55/lib/Perturbations/resDirectProductLazy.gi as follows:
<code>
#if Parent(G)=Parent(H) and not G=H  then       #DELETE
if One(G) in H and not G=H then                 #ADD
</code>


I'm planning on releasing hap-1.56 soon and I'll include this change.

**Comment by BrauerSuzuki** [comment]
Thanks for the quick fix (on Sunday!)
