### ISSUE TITLE
Implement `LoadKernelExtension`

### ISSUE THREAD

**Issue by limakzi** [gap-packages/hap#123]
Be so kind and implement `LoadKernelExtension("", "")` methods, so it can be aligned with `GAP-4.12`.

https://github.com/gap-system/gap/issues/5761

**Comment by fingolfin** [comment]
I am not sure `LoadKernelExtension` is really appropriate for the usecase in hap...

**Comment by limakzi** [comment]
For sure, modules are loaded.
https://github.com/gap-packages/hap/blob/master/read.g#L44

**Comment by fingolfin** [comment]
I know, but these are not usual kernel extension but gac output and not in use by normal users. (Actually I wonder if @grahamknockillaree uses this code at all? Perhaps it could just be removed)

**Comment by grahamknockillaree** [comment]
I agree with @fingolfin that, since the modules are only ever created and loaded when the user wants a gac compiled version of Hap, it's maybe not necessary to use LoadKernelExtension and IsKernelExtensionAvailable . A typical user won't use gac.  So I propose to close this issue.

I do remember that for a few functions (I think relating to homotopy contractions of pure cubical complexes) the use of gac produced a noticeable speedup. I'll try to identify what kind of speedups can be obtained and consider how worthwhile it is to keep the gac option for Hap.
