### ISSUE TITLE
Tests of HAP 1.24 failing in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#26]
I think I've reported this before, but don't remember where. See https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/624910457 when GAP is started with `-A`:

```
########> Diff in /home/gap/inst/gap-master/pkg/hap-1.22/tst/testall/hap.tst:
21
# Input is:
R:=ResolutionAbelianGroup([0,0,0],5);;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `*' on 2 arguments
########
```

**Comment by grahamknockillaree** [comment]
This error seems to no longer happen. I've changed a few things in the test files, but I'm not sure which of the changes 'solved' this problem

**Comment by alex-konovalov** [comment]
@grahamknockillaree well, it's hard to say now - HAP has quite complicated dependencies, and tests fail in Jenkins in St Andrews, but maybe because of some dependencies missing, and they fail in Travis, because of some complicated example, which takes a long time (`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`). I have created #31 to remind of this.

At least the builds at https://travis-ci.org/github/gap-packages/hap pass...

**Comment by grahamknockillaree** [comment]
I realize that some of the HAP tests require way too much memory and I'm looking into this. Yesterday I went through the test outputs on my local computer and moved all .tst files requiring more that 1Gb to tst/testall2.  Then, in testall.g I added a line that skipped tst/testall2 if the 32-bit version of GAP is being used.

But what I plan to do is to tweak .tst files in tst/testall2 so that they require less memory but test the same functions. After each tweak I'll move the file back from doc/testall2 to tst/testall.
